version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    working_directory: ~/LeanAgileFlowDashboard
    docker:
      - image: circleci/node:9.5-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: angular-build
          command: yarn ng build --prod --aot --no-progress
      - run:
          name: angular-test
          command: yarn test --watch=false --code-coverage --progress=false
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: ./coverage
      - store_test_results:
          path: ./coverage
      - run:
          name: angular-lint
          command: yarn lint --format junit | sed -n '3p' > tslint-output-junit.xml
      - store_artifacts:
          path: tslint-output-junit.xml
          prefix: lint`
      - codecov/upload:
          file: ./coverage/lcov.info
